Repository ArcherHuang/e-commerce, pull requests merged in 2019-11, with the labels that each got.

#274 Fix bug/be-admin-message, fix #273
  controllers/hbs/productController.js
  views/index.hbs
Labels: bug

#276 Fix doc/readme, fix #275
  README.md
Labels: documentation

#278 Fix feature/updated-forgotpassword-email-link-not-use, fix #277
  services/forgotPasswordService.js
Labels: enhancement

#282 Fix feature/cart-page-login-redirect-cart-page, fix #280
  controllers/hbs/accountController.js
  controllers/hbs/cartController.js
Labels: enhancement

#283 Fix enhancement/forgotpassword-email-content, fix #281
  services/forgotPasswordService.js
Labels: enhancement

#284 Fix/fe pages
  controllers/hbs/productController.js
  public/assets/images/logo/logo.png
  views/ordersNewebPayment.hbs
  views/ordersStripePayment.hbs
  views/partials/index/banner.hbs
  views/partials/index/discountArea.hbs
  views/partials/navBar.hbs
  views/partials/productCard.hbs
  views/partials/productDetail/productDetailCard.hbs
Labels: enhancement

#285 try to fix #271
  services/productService.js
Labels: bug

#286 將搜尋商品關鍵字範圍鎖定在商品名稱
  services/productService.js
Labels: enhancement

#287 Fix bug/cart-item-remove-readd-same-item, fix #279
  services/cartService.js
Labels: bug

#288 若搜尋無商品，顯示提示訊息
  views/partials/productCard.hbs
Labels: enhancement

#293 update footer, fix #209 #219 #292
  views/partials/footer.hbs
Labels: bug

#302 fix getCart function for new users, close #289
  services/cartService.js
Labels: bug

#304 add console.log for checking errors
  config/passport.js
  controllers/hbs/productController.js
Labels: bug

#305 add console.log for testing
  config/passport.js
  controllers/hbs/accountController.js
  routes/hbs/authRoute.js
  services/userService.js
Labels: bug

#306 測試轉址功能
  routes/hbs/authRoute.js
Labels: bug

#307 恢復恢復fb登入功能，但是會導到heroku網址
  config/passport.js
  controllers/hbs/productController.js
  routes/hbs/authRoute.js
  services/userService.js
Labels: bug

#310 Fix/fe pages
  controllers/hbs/orderController.js
  services/orderService.js
  views/carts.hbs
  views/ordersNewebPayment.hbs
  views/ordersStripePayment.hbs
  views/partials/productCard.hbs
  views/partials/productDetail/productDetailCard.hbs
  views/partials/shop/searchWidget.hbs
Labels: enhancement

#313 update readme
  README.md
  project-intro.md
Labels: feature

#316 Fix bug/swagger-return-html, fix #315
  routes/routes.js
Labels: bug

#320 db/ikea-seeders, fix #319
  ikea_data/items.csv
  ikea_data/products.json
  ikea_data/readCSVToJSONAndS3.js
  package-lock.json
  package.json
  seeders/20191007095350-demo-users.js
Labels: enhancement

#322 modify migration for Orders table
  migrations/20191111125211-fix-order-model.js
Labels: bug

#324 try to fix #323
  models/review.js
Labels: bug

#328 Fix/data presenting
  services/admin/orderService.js
  views/accountsOrders.hbs
Labels: bug

#329 bug/not-match-route, fix #326
  routes/index.js
  routes/routes.js
Labels: bug

#331 修正評論功能與頁面顯示, close #330
  controllers/hbs/productController.js
  services/productService.js
  views/partials/productDetail/productDetailCard.hbs
Labels: bug

#332 fix sorting function for tables
  public/javascripts/sorting.js
  views/accountsCoupons.hbs
  views/accountsOrderDetails.hbs
  views/accountsOrders.hbs
  views/accountsReviews.hbs
  views/accountsWishList.hbs
  views/admin/categories.hbs
  views/admin/coupons.hbs
  views/admin/discounts.hbs
  views/admin/notifications.hbs
  views/admin/orderDetails.hbs
  views/admin/orders.hbs
  views/admin/products.hbs
  views/admin/users.hbs
  views/layouts/main.hbs
Labels: bug

#334 bug/display-time-is-Taipei, fix #333
  config/handlebars-helpers.js
Labels: bug

#336 add time column to admin/orders data table, close #335
  views/admin/orders.hbs
Labels: enhancement

#339 fix typo, close #338
  services/cronService.js
Labels: bug
